[2022-01-07 18:35:47,872] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: verificacao_log.verificacao_log manual__2022-01-07T18:35:39.433868+00:00 [queued]>
[2022-01-07 18:35:47,882] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: verificacao_log.verificacao_log manual__2022-01-07T18:35:39.433868+00:00 [queued]>
[2022-01-07 18:35:47,882] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2022-01-07 18:35:47,882] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2022-01-07 18:35:47,882] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-01-07 18:35:47,898] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): verificacao_log> on 2022-01-07 18:35:39.433868+00:00
[2022-01-07 18:35:47,902] {standard_task_runner.py:52} INFO - Started process 690 to run task
[2022-01-07 18:35:47,908] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'verificacao_log', 'verificacao_log', 'manual__2022-01-07T18:35:39.433868+00:00', '--job-id', '128', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmp3hof8cv6', '--error-file', '/tmp/tmphdu0cn24']
[2022-01-07 18:35:47,908] {standard_task_runner.py:77} INFO - Job 128: Subtask verificacao_log
[2022-01-07 18:35:48,005] {logging_mixin.py:109} INFO - Running <TaskInstance: verificacao_log.verificacao_log manual__2022-01-07T18:35:39.433868+00:00 [running]> on host fa901b562f08
[2022-01-07 18:35:48,104] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=verificacao_log
AIRFLOW_CTX_TASK_ID=verificacao_log
AIRFLOW_CTX_EXECUTION_DATE=2022-01-07T18:35:39.433868+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-01-07T18:35:39.433868+00:00
[2022-01-07 18:35:52,327] {logging_mixin.py:109} INFO - Data atual:  2022-01-07 18:35:52.327409
[2022-01-07 18:35:52,327] {logging_mixin.py:109} INFO - Dia do ultimo log:  2021/12/10 17:10:14
[2022-01-07 18:35:52,327] {logging_mixin.py:109} INFO - Tempo entre o ultimo log e a data atual:  28 days, 1:25:38.327353
[2022-01-07 18:35:52,327] {logging_mixin.py:109} INFO - INFO   | jvm 4    | 2021/12/10 17:10:14 | [RSFILEMANAGERSERVER] Finalizando importacao lote: DadosSite_03105116_49301_2021121416h55min05seg.zip.rscd. Tempo gasto (ms): 15944
[2022-01-07 18:35:52,328] {logging_mixin.py:109} INFO - 
[2022-01-07 18:35:52,328] {logging_mixin.py:109} INFO - 
[2022-01-07 18:35:52,328] {logging_mixin.py:109} INFO - 
[2022-01-07 18:35:52,328] {logging_mixin.py:109} INFO - Erro, tempo entre ultimo log e data atual maior que:  0:10:00
[2022-01-07 18:35:52,328] {python.py:152} INFO - Done. Returned value was: None
[2022-01-07 18:35:52,348] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=verificacao_log, task_id=verificacao_log, execution_date=20220107T183539, start_date=20220107T183547, end_date=20220107T183552
[2022-01-07 18:35:52,425] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-07 18:35:52,529] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
